# Generated by Django 5.1.5 on 2025-02-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stqpictures', '0003_service_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('music_video', 'Music Video'), ('documentary', 'Documentary'), ('motivation', 'Motivation'), ('films', 'Films'), ('craft', 'Craft')], default='music_video', max_length=20)),
                ('upload_link', models.URLField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
